// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusteriWebProject.Models;

namespace MusteriWebProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230211221531_deneme")]
    partial class deneme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusteriWebProject.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminAd")
                        .HasColumnType("Varchar(20)");

                    b.Property<int>("Sifre")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.ToTable("Admins_Information");
                });

            modelBuilder.Entity("MusteriWebProject.Models.CustomerC", b =>
                {
                    b.Property<int>("CustKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adı")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("AramaTarihi")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("GorusmeSonucu")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Kampanya")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("KayitTarihiBaslangici")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("KayitTarihiBitisi")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Kaynak")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<string>("Soyadı")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<long>("TelefonNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Temsilci")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("CustKey");

                    b.ToTable("Customers_Information");
                });
#pragma warning restore 612, 618
        }
    }
}
